#!/bin/bash

list="ainc cvai dran 4"
set 1 2 3
for var in $list
do
  set $2 $1 $3 $var 5
  done
  echo $1
  if test $4 –gt 4
  then    shift 1
    echo $4
               true
               else     shift 0
               echo $3
                          false
                          fi
                          echo $?
